# @generated
load("@antlir//antlir/antlir2/package_managers/dnf/rules:rpm.bzl", "rpm")
load("@antlir//antlir/antlir2/package_managers/dnf/rules:xml.bzl", "xml")
rpm(name='0-4.0.8-15.el9.noarch-75d38', rpm_name='python3-zope-exceptions', epoch=0, version='4.0.8', release='15.el9', arch='noarch', url='https://mirror.facebook.net/fedora/epel/9/Everything/x86_64/Packages/p/python3-zope-exceptions-4.0.8-15.el9.noarch.rpm', xml=':0-4.0.8-15.el9.noarch-75d38--xml', sha1=None, sha256='75d388b3ff116d0c7e68cff6d29c3b301bd76f08a44c4dc8df30113657c2b11d', visibility=['//snapshot/rpm/centos9/...'])
xml(name='0-4.0.8-15.el9.noarch-75d38--xml', primary='<package type="rpm">\n  <name>python3-zope-exceptions</name>\n  <arch>noarch</arch>\n  <version epoch="0" ver="4.0.8" rel="15.el9"/>\n  <checksum type="sha256" pkgid="YES">75d388b3ff116d0c7e68cff6d29c3b301bd76f08a44c4dc8df30113657c2b11d</checksum>\n  <summary>Zope Exceptions</summary>\n  <description>This package contains exception interfaces and implementations which are so\ngeneral purpose that they don\'t belong in Zope application-specific packages.</description>\n  <packager>Fedora Project</packager>\n  <url>http://pypi.python.org/pypi/zope.exceptions</url>\n  <time file="1694641745" build="1694575644"/>\n  <size package="25357" installed="47587" archive="53112"/>\n  <location href="Packages/75d388b3ff116d0c7e68cff6d29c3b301bd76f08a44c4dc8df30113657c2b11d/python3-zope-exceptions-0:4.0.8-15.el9.noarch.rpm"/>\n  <format>\n    <rpm:license>ZPLv2.1</rpm:license>\n    <rpm:vendor>Fedora Project</rpm:vendor>\n    <rpm:group>Unspecified</rpm:group>\n    <rpm:buildhost>buildvm-x86-12.iad2.fedoraproject.org</rpm:buildhost>\n    <rpm:sourcerpm>python-zope-exceptions-4.0.8-15.el9.src.rpm</rpm:sourcerpm>\n    <rpm:header-range start="4504" end="12617"/>\n    <rpm:provides>\n      <rpm:entry name="python-zope-exceptions" flags="EQ" epoch="0" ver="4.0.8" rel="15.el9"/>\n      <rpm:entry name="python3-zope-exceptions" flags="EQ" epoch="0" ver="4.0.8" rel="15.el9"/>\n      <rpm:entry name="python3.9-zope-exceptions" flags="EQ" epoch="0" ver="4.0.8" rel="15.el9"/>\n      <rpm:entry name="python3.9dist(zope-exceptions)" flags="EQ" epoch="0" ver="4.0.8"/>\n      <rpm:entry name="python3.9dist(zope.exceptions)" flags="EQ" epoch="0" ver="4.0.8"/>\n      <rpm:entry name="python3dist(zope-exceptions)" flags="EQ" epoch="0" ver="4.0.8"/>\n      <rpm:entry name="python3dist(zope.exceptions)" flags="EQ" epoch="0" ver="4.0.8"/>\n    </rpm:provides>\n    <rpm:requires>\n      <rpm:entry name="python(abi)" flags="EQ" epoch="0" ver="3.9"/>\n      <rpm:entry name="python3-zope-interface"/>\n      <rpm:entry name="python3.9dist(setuptools)"/>\n      <rpm:entry name="python3.9dist(zope-interface)"/>\n    </rpm:requires>\n    <rpm:obsoletes>\n      <rpm:entry name="python-zope-exceptions" flags="LT" epoch="0" ver="4.0.8" rel="15.el9"/>\n      <rpm:entry name="python39-zope-exceptions" flags="LT" epoch="0" ver="4.0.8" rel="15.el9"/>\n    </rpm:obsoletes>\n  </format>\n</package>\n', filelists='<package pkgid="75d388b3ff116d0c7e68cff6d29c3b301bd76f08a44c4dc8df30113657c2b11d" name="python3-zope-exceptions" arch="noarch">\n  <version epoch="0" ver="4.0.8" rel="15.el9"/>\n  <file type="dir">/usr/lib/python3.9/site-packages/zope</file>\n  <file>/usr/lib/python3.9/site-packages/zope.exceptions-4.0.8-py3.9-nspkg.pth</file>\n  <file type="dir">/usr/lib/python3.9/site-packages/zope.exceptions-4.0.8-py3.9.egg-info</file>\n  <file>/usr/lib/python3.9/site-packages/zope.exceptions-4.0.8-py3.9.egg-info/PKG-INFO</file>\n  <file>/usr/lib/python3.9/site-packages/zope.exceptions-4.0.8-py3.9.egg-info/SOURCES.txt</file>\n  <file>/usr/lib/python3.9/site-packages/zope.exceptions-4.0.8-py3.9.egg-info/dependency_links.txt</file>\n  <file>/usr/lib/python3.9/site-packages/zope.exceptions-4.0.8-py3.9.egg-info/namespace_packages.txt</file>\n  <file>/usr/lib/python3.9/site-packages/zope.exceptions-4.0.8-py3.9.egg-info/not-zip-safe</file>\n  <file>/usr/lib/python3.9/site-packages/zope.exceptions-4.0.8-py3.9.egg-info/requires.txt</file>\n  <file>/usr/lib/python3.9/site-packages/zope.exceptions-4.0.8-py3.9.egg-info/top_level.txt</file>\n  <file type="dir">/usr/lib/python3.9/site-packages/zope/exceptions</file>\n  <file>/usr/lib/python3.9/site-packages/zope/exceptions/__init__.py</file>\n  <file type="dir">/usr/lib/python3.9/site-packages/zope/exceptions/__pycache__</file>\n  <file>/usr/lib/python3.9/site-packages/zope/exceptions/__pycache__/__init__.cpython-39.opt-1.pyc</file>\n  <file>/usr/lib/python3.9/site-packages/zope/exceptions/__pycache__/__init__.cpython-39.pyc</file>\n  <file>/usr/lib/python3.9/site-packages/zope/exceptions/__pycache__/exceptionformatter.cpython-39.opt-1.pyc</file>\n  <file>/usr/lib/python3.9/site-packages/zope/exceptions/__pycache__/exceptionformatter.cpython-39.pyc</file>\n  <file>/usr/lib/python3.9/site-packages/zope/exceptions/__pycache__/interfaces.cpython-39.opt-1.pyc</file>\n  <file>/usr/lib/python3.9/site-packages/zope/exceptions/__pycache__/interfaces.cpython-39.pyc</file>\n  <file>/usr/lib/python3.9/site-packages/zope/exceptions/__pycache__/log.cpython-39.opt-1.pyc</file>\n  <file>/usr/lib/python3.9/site-packages/zope/exceptions/__pycache__/log.cpython-39.pyc</file>\n  <file>/usr/lib/python3.9/site-packages/zope/exceptions/exceptionformatter.py</file>\n  <file>/usr/lib/python3.9/site-packages/zope/exceptions/interfaces.py</file>\n  <file>/usr/lib/python3.9/site-packages/zope/exceptions/log.py</file>\n  <file type="dir">/usr/share/doc/python3-zope-exceptions</file>\n  <file>/usr/share/doc/python3-zope-exceptions/CHANGES.rst</file>\n  <file>/usr/share/doc/python3-zope-exceptions/COPYRIGHT.txt</file>\n  <file>/usr/share/doc/python3-zope-exceptions/LICENSE.txt</file>\n  <file>/usr/share/doc/python3-zope-exceptions/README.rst</file>\n</package>\n', other='<package pkgid="75d388b3ff116d0c7e68cff6d29c3b301bd76f08a44c4dc8df30113657c2b11d" name="python3-zope-exceptions" arch="noarch">\n  <version epoch="0" ver="4.0.8" rel="15.el9"/>\n  <changelog author="Fedora Release Engineering &lt;releng@fedoraproject.org&gt; - 4.0.8-9" date="1518177600">- Rebuilt for https://fedoraproject.org/wiki/Fedora_28_Mass_Rebuild</changelog>\n  <changelog author="Miro Hron&#x10D;ok &lt;mhroncok@redhat.com&gt; - 4.0.8-10" date="1529236800">- Rebuilt for Python 3.7</changelog>\n  <changelog author="Fedora Release Engineering &lt;releng@fedoraproject.org&gt; - 4.0.8-11" date="1531569600">- Rebuilt for https://fedoraproject.org/wiki/Fedora_29_Mass_Rebuild</changelog>\n  <changelog author="Fedora Release Engineering &lt;releng@fedoraproject.org&gt; - 4.0.8-12" date="1549108800">- Rebuilt for https://fedoraproject.org/wiki/Fedora_30_Mass_Rebuild</changelog>\n  <changelog author="Fedora Release Engineering &lt;releng@fedoraproject.org&gt; - 4.0.8-13" date="1564142400">- Rebuilt for https://fedoraproject.org/wiki/Fedora_31_Mass_Rebuild</changelog>\n  <changelog author="Miro Hron&#x10D;ok &lt;mhroncok@redhat.com&gt; - 4.0.8-14" date="1565956800">- Rebuilt for Python 3.8</changelog>\n  <changelog author="Miro Hron&#x10D;ok &lt;mhroncok@redhat.com&gt; - 4.0.8-15" date="1568980800">- Subpackage python2-zope-exceptions has been removed\n  See https://fedoraproject.org/wiki/Changes/Mass_Python_2_Package_Removal</changelog>\n</package>\n')
